#!/usr/bin/env bash
# Launch zoom-out IC LoRA training on GPUs 0-5.
# Run with no arguments: bash train.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HERE" && git rev-parse --show-toplevel)"
LTX_TRAINER="$REPO_ROOT/LTX2/src/packages/ltx-trainer"
CONFIGS_DIR="$HERE/configs"
DATASETS_DIR="$HERE/datasets"
OUTPUTS_DIR="$HERE/outputs"

mkdir -p "$CONFIGS_DIR" "$OUTPUTS_DIR"

# --- Generate accelerate config ---
ACCEL_CFG="$CONFIGS_DIR/accelerate_ddp.yaml"
if [ ! -f "$ACCEL_CFG" ]; then
echo "Generating accelerate config: $ACCEL_CFG"
cat > "$ACCEL_CFG" << 'EOF'
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 6
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
EOF
fi

# --- Pick validation videos from test set ---
TEST_JSON="$DATASETS_DIR/test_set.json"
if [ ! -f "$TEST_JSON" ]; then
    echo "ERROR: $TEST_JSON not found. Run prepare_dataset.py first."
    exit 1
fi

# Extract first 4 test videos for validation (using python one-liner)
VALIDATION_BLOCK=$(python3 -c "
import json
with open('$TEST_JSON') as f:
    tests = json.load(f)
prompts = []
refs = []
for t in tests[:4]:
    prompts.append('    - \"' + t['caption'][:200].replace('\"', '\\\\\"') + '\"')
    refs.append('    - \"' + t['reference_path'] + '\"')
print('  prompts:')
for p in prompts: print(p)
print('  reference_videos:')
for r in refs: print(r)
")

# --- Generate training config ---
TRAIN_CFG="$CONFIGS_DIR/zoom_out_ic_lora.yaml"
echo "Generating training config: $TRAIN_CFG"
cat > "$TRAIN_CFG" << EOF
# Zoom-Out IC LoRA Training Config (auto-generated by train.sh)
model:
  model_path: "$REPO_ROOT/LTX2/models/ltx-2-19b-dev.safetensors"
  text_encoder_path: "$REPO_ROOT/LTX2/models/gemma-3-12b-it-qat-q4_0-unquantized"
  training_mode: "lora"

lora:
  rank: 32
  alpha: 32
  dropout: 0.0
  target_modules:
    - "attn1.to_k"
    - "attn1.to_q"
    - "attn1.to_v"
    - "attn1.to_out.0"
    - "attn2.to_k"
    - "attn2.to_q"
    - "attn2.to_v"
    - "attn2.to_out.0"
    - "ff.net.0.proj"
    - "ff.net.2"

training_strategy:
  name: "video_to_video"
  first_frame_conditioning_p: 0.2
  reference_latents_dir: "reference_latents"

optimization:
  learning_rate: 2e-5
  steps: 100000
  batch_size: 1
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  optimizer_type: "adamw"
  scheduler_type: "linear"
  scheduler_params: {}
  enable_gradient_checkpointing: true

acceleration:
  mixed_precision_mode: "bf16"
  quantization: null
  load_text_encoder_in_8bit: false

data:
  preprocessed_data_root: "$DATASETS_DIR/.precomputed"
  num_dataloader_workers: 2

validation:
$VALIDATION_BLOCK
  video_dims: [512, 320, 121]
  frame_rate: 24.0
  inference_steps: 30
  guidance_scale: 4.0
  stg_scale: 1.0
  stg_blocks: [29]
  stg_mode: "stg_v"
  interval: 500
  include_reference_in_output: true
  videos_per_prompt: 1
  seed: 42
  generate_audio: false
  skip_initial_validation: false

checkpoints:
  interval: 500
  keep_last_n: -1
  precision: "bfloat16"

flow_matching:
  timestep_sampling_mode: "shifted_logit_normal"
  timestep_sampling_params: {}

output_dir: "$OUTPUTS_DIR"
seed: 42
EOF

echo ""
echo "======================================================================"
echo "  Launching IC LoRA training on GPUs 0-5"
echo "  Config:  $TRAIN_CFG"
echo "  Accel:   $ACCEL_CFG"
echo "  Output:  $OUTPUTS_DIR"
echo "======================================================================"
echo ""

cd "$LTX_TRAINER"
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 \
uv run accelerate launch \
    --config_file "$ACCEL_CFG" \
    scripts/train.py "$TRAIN_CFG"
